/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Main', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
            mainPanel: 'mainpanel',
            article: 'article',
            list:'#articleList',
            articleList:'#articlePanel',
            titlebar:'#titlebar',
            backButton:'#titlebar #prevButton',
        },

        control: {
            "#articleList" :{
            	itemtap: 'onArticleTap'
            },
            '[action=back]':{
            	tap: 'onBackButtonTap'
            }
        }
    },
    
    onArticleTap: function(dataview, index, target, record, e, options){
    	this.getMainPanel().animateActiveItem(1, { type: "slide", direction: "left" });
    	this.getArticleList().setData(record.data);
    	this.getTitlebar().setTitle("기사 전문");
    	//this.getBackButton.show();
    	
    },
    
    onBackButtonTap: function(button, event){
    	console.log("dd");
    	this.getMainPanel().setActiveItem(0);
    	this.getList().deselectAll();
    }

});