/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Main', {
    extend: 'Ext.app.Controller',
    
    start:function(){
    		alert("start");
    },
    
    config: {
        refs: {
            mainPanel: 'mainpanel',
            article: 'article',
            list:'#articleList',
            articleList:'#articlePanel',
            titlebar:'#titlebar',
            backButton:'#prevButton',
            detailArticle:'#detailArticle',
            newsListTopImage:'#newsListTopImage',
            feedIcon:"#feedIcon",
            main:"#main",
            homeButton:"#homeButton",
        },

        control: {
            "#articleList" :{
            	itemtap: 'onArticleTap'
            },
            '[action=back]':{
            	tap: 'onBackButtonTap'
            },
            '#article_font_size_up':{
            	tap:'font_size_up'
            },
            '#article_font_size_down':{
            	tap:'font_size_down'
            },
            feedIcon:{
            	itemtap:'feedIconTap',
            },
            homeButton:{
            	tap:"homeButtonTap",
            },
        }
    },
    
    homeButtonTap:function(button, event){
    	this.getMain().setActiveItem(0);
    	Ext.getCmp("homeButton").hide();
    	this.getList().deselectAll();
    },
    
    feedIconTap:function(list, index, item, e){
    	if(index=="0"){
    		this.getMain().animateActiveItem(3, {type:"slide", direction:"left"});
    	}else{
    		this.getMain().animateActiveItem(1, {type:"slide", direction:"left"});
    	}
    	console.log("tap!!");
    	Ext.getCmp("homeButton").show();
    },
    
    launch: function(app) {
    	//console.log(Ext.getStore("Feed").data.keys.length);
        test = {url:"이미지 주소", title:"타이틀"};
        //this.getNewsListTopImage().setData(test);
    },
    
    onArticleTap: function(dataview, index, target, record, e, options){
    	this.getMain().animateActiveItem(2, { type: "slide", direction: "left" });
    	this.getArticleList().setData(record.data);
    	this.getTitlebar().setTitle(record.data.title);
    	Ext.getCmp("prevButton").show();
    	
    	localStorage.flag = index;
    },
    
    onBackButtonTap: function(button, event){
    	this.getMain().setActiveItem(1);
    	this.getList().deselectAll();
    	this.getTitlebar().setTitle("News");
    	Ext.getCmp("prevButton").hide();
    },
    
    font_size_up: function(button, event){
    	var current = parseInt($("#mainArticle").css("font-size"));
    	console.log(current);
    	$("#mainArticle").css("font-size", (++current) + "px");
    },
    
    font_size_down: function(button, event){
    	var current = parseInt($("#mainArticle").css("font-size"));
    	console.log(current);
    	$("#mainArticle").css("font-size", (--current) + "px");
    }
});