/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Main', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
            mainPanel: 'mainpanel',
            article: 'article',
            list:'#articleList',
            articleList:'#articlePanel',
            titlebar:'#titlebar',
            backButton:'#prevButton',
            detailArticle:'#detailArticle',
            newsListTopImage:'#newsListTopImage',
        },

        control: {
            "#articleList" :{
            	itemtap: 'onArticleTap'
            },
            '[action=back]':{
            	tap: 'onBackButtonTap'
            },
            '#getTopImage':{
            	tap:'getImage',
            },
            '#article_font_size_up':{
            	tap:'font_size_up'
            },
            '#article_font_size_down':{
            	tap:'font_size_down'
            }
        }
    },
    
    launch: function(app) {
        console.log(Ext.getStore("Feed").data.length);
        test = {url:"d", title:"a"};
        this.getNewsListTopImage().setData(test);
    },
    
    onArticleTap: function(dataview, index, target, record, e, options){
    	this.getMainPanel().animateActiveItem(1, { type: "slide", direction: "left" });
    	this.getArticleList().setData(record.data);
    	this.getTitlebar().setTitle(record.data.title);
    	Ext.getCmp("prevButton").show();
    	
    	localStorage.flag = index;
    },
    
    onBackButtonTap: function(button, event){
    	this.getMainPanel().setActiveItem(0);
    	this.getList().deselectAll();
    	this.getTitlebar().setTitle("News");
    	Ext.getCmp("prevButton").hide();
    },
    
    getImage: function(button, event){
    	
    },
    
    font_size_up: function(button, event){
    	var current = parseInt($("#mainArticle").css("font-size"));
    	console.log(current);
    	$("#mainArticle").css("font-size", (++current) + "px");
    },
    
    font_size_down: function(button, event){
    	var current = parseInt($("#mainArticle").css("font-size"));
    	console.log(current);
    	$("#mainArticle").css("font-size", (--current) + "px");
    }
});